name: miscellaneous
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - pip
  - dask
  - scikit-learn
  - numpy>=1.25.*
  - pandas>=2.0.*
  - scipy>=1.11.*
  - pyyaml
  - requests
  - pytest
  - coverage
  - pylint
  - pytest-cov
  - flake8