name: pollutants
channels:
  - conda-forge
dependencies:
  - python==3.11.7
  - pip
  - dask>=2023.11
  - scikit-learn
  - numpy>=1.25.*
  - pandas>=2.0.*
  - scipy>=1.11.*
  - requests>=2.31.*
  - pytest
  - coverage
  - pytest-cov
  - pylint
  - flake8