# S3: Endpoints -> https://docs.aws.amazon.com/general/latest/gr/s3.html
parameters:
  region_name: 'eu-west-1'
  location_constraint: '{region_name}'
  access_control_list: 'private'
  bucket_name: 'pollutants'
  points_: 'points/'
  references_: 'references/'